---
parsl_log_level: WARNING
retries: 0
make_symlinks: false

ModelEvaluation:
  gpu: false
  use_threadpool: true
  max_simulation_time: 0.4
  
ModelTraining:
  gpu: true
  use_threadpool: true
  max_training_time: 1
  max_workers: 1  # suppress assertion for multigpu training
CP2K:

  cores_per_worker: 2
  max_evaluation_time: 0.5
  container_uri: 'oras://ghcr.io/molmod/cp2k:2024.1'
  
GPAW:
  cores_per_worker: 2
  max_evaluation_time: 0.5
  container_uri: 'oras://ghcr.io/molmod/gpaw:24.1'
  
ORCA:
  cores_per_worker: 2
  max_evaluation_time: 0.5


...
