---
psiflow_log_level: INFO

ModelEvaluation:
    executor: threadpool
    max_threads: 4
    max_runtime: 00:00:20
    
ModelTraining:
    executor: threadpool
    max_threads: 4
    max_runtime: 00:00:20

  
CP2K:
  executor: workqueue
  cores_per_task: 2
  max_runtime: 00:00:20
  memory_limit: 2
  container:
    uri: docker://cp2k/cp2k:2025.2_mpich_x86_64_psmp
  
GPAW:
  executor: workqueue
  cores_per_task: 2
  container:
    uri: oras://ghcr.io/molmod/gpaw:24.1
  
ORCA:
  executor: workqueue
  cores_per_task: 2


...
