---
parsl_log_level: WARNING
container_engine: 'singularity'
container_uri: 'oras://ghcr.io/molmod/psiflow:4.0.0_rocm6.2'
default_threads: 8
CP2K:
  cores_per_worker: 32
  max_evaluation_time: 20
  launch_command: 'singularity exec -e --no-init oras://ghcr.io/molmod/cp2k:2024.1 /opt/entry.sh mpirun -np 32 cp2k.psmp'
  slurm:
    partition: "standard"
    account: "project_465001125"
    nodes_per_block: 1
    cores_per_node: 128
    max_blocks: 10
    walltime: "01:00:00"
ModelEvaluation:
  cores_per_worker: 7
  gpu: True
  slurm:
    partition: "standard-g"
    account: "project_465001125"
    nodes_per_block: 1
    cores_per_node: 56
    max_blocks: 10
    walltime: "01:00:00"
    scheduler_options: "#SBATCH --gres=gpu:8\n"
ModelTraining:
  cores_per_worker: 7
  gpu: true
  multigpu: true
  slurm:
    partition: "standard-g"
    account: "project_465001125"
    nodes_per_block: 1
    cores_per_node: 56
    walltime: "01:00:00"
    scheduler_options: "#SBATCH --gres=gpu:8\n"
...
