name: CI
run-name: pytest-CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test-py310:
    runs-on: ubuntu-24.04
    steps:
      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.6
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '2.0.5-0'
          environment-name: 'test-env'
          generate-run-shell: true
          create-args: >-
            python=3.10
            ndcctools==7.14.0
            py-plumed
            simple-dftd3
            dftd3-python
            pip
            -c conda-forge
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'
      
      - name: Install pip dependencies
        run: |
          pip install pyfftw colorcet wandb pandas plotly plumed 'numpy<2.0.0'
          pip install --no-cache-dir git+https://github.com/i-pi/i-pi.git@v3.0.0-beta4
          pip install torch==2.5.1
          pip install git+https://github.com/acesuit/MACE.git@v0.3.5
        # pip install 'psiflow[dev] @ git+https://github.com/molmod/psiflow.git'

      - name: Checkout specific commit
        uses: actions/checkout@v4
        
      - run: ls -a
      
      - name: Install Psiflow
        run: |
          pip install .[dev]
          # cd psiflow
          pytest --skip-gpu --psiflow-config=.github/threadpool.yaml
        shell: micromamba-shell {0}


      # - name: Download container images
      #   run: |
      #     apptainer exec oras://ghcr.io/molmod/cp2k:2024.1 ls
      #     apptainer exec oras://ghcr.io/molmod/gpaw:24.1 ls
      # - name: Run test suite
      #   env:
      #     WANDB_API_KEY: secrets.WANDB_API_KEY
      #   shell: micromamba-shell {0}
      #   run: |
      #     cd ${{ runner.temp }}
      #     git clone https://github.com/molmod/psiflow
      #     cd psiflow
      #     pytest --skip-gpu --psiflow-config=.github/threadpool.yaml
          
        
      # - name: install pip dependencies and execute pytest
      #   run: |
      #     pip install pyfftw colorcet wandb pandas plotly plumed 'numpy<2.0.0'
      #     pip install --no-cache-dir git+https://github.com/i-pi/i-pi.git@v3.0.0-beta4
      #     pip install git+https://github.com/acesuit/MACE.git@v0.3.5
      #     pip install 'psiflow[dev] @ git+https://github.com/molmod/psiflow.git'
      #     cd ${{ runner.temp }} && git clone https://github.com/molmod/psiflow
      #     cd psiflow
      #     export WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}
      #     apptainer exec oras://ghcr.io/molmod/cp2k:2024.1 ls
      #     apptainer exec oras://ghcr.io/molmod/gpaw:24.1 ls
      #     pytest --skip-gpu --psiflow-config=.github/threadpool.yaml
      #   shell: micromamba-shell {0}
