name: CI
run-name: pytest-CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test-py310:
    runs-on: ubuntu-24.04
    steps:
      - uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.6
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '2.0.5-0'
          environment-name: 'test-env'
          generate-run-shell: true
          create-args: >-
            python=3.10
            ndcctools==7.14.0
            py-plumed
            simple-dftd3
            dftd3-python
            pip
            -c conda-forge
          init-shell: bash
          cache-environment: true
          post-cleanup: 'all'
      - name: Install dependencies and download containers
        shell: micromamba-shell {0}
        run: |
          which pip
          pip install pyfftw colorcet wandb pandas plotly plumed 'numpy<2.0.0'
          pip install --no-cache-dir git+https://github.com/i-pi/i-pi.git@v3.0.0-beta4
          pip install torch==2.5.1
          pip install git+https://github.com/acesuit/MACE.git@v0.3.5
          apptainer exec oras://ghcr.io/molmod/cp2k:2024.1 ls
          apptainer exec oras://ghcr.io/molmod/gpaw:24.1 ls
      - name: Checkout specific commit
        uses: actions/checkout@v4
      - name: Install Psiflow and run tests
        shell: micromamba-shell {0}
        env:
          WANDB_API_KEY: secrets.WANDB_API_KEY
          WANDB_MODE: offline                        # disables WandB server calls
        run: |
          pip install .[dev]
          pip list
          pytest --skip-gpu --psiflow-config=.github/threadpool.yaml
